#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <filename>"
    exit 1
fi

filename="$1"
ext1=".asm"
ext2=".com"
backup_dir_name="backup/"

if [ ! -d "$backup_dir_name" ]; then
	mkdir "$backup_dir_name"
fi

cp "$filename$ext1" backup/
rm -f "floppy.img"

nasm -f bin -o "$filename$ext2" "$filename$ext1"
truncate -s 1474560 "$filename$ext2"
mv "$filename$ext2" floppy.img
